name = "butteurbot"
main = "src/index.ts"
compatibility_date = "2025-01-13"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[triggers]
crons = [
  "0 20 * * *",  # 4:00 PM EDT (20:00 UTC)
  "0 21 * * *",  # 4:00 PM EST (21:00 UTC)
  "0 2 * * *",   # 10:00 PM EDT (02:00 UTC next day)
  "0 3 * * *"    # 10:00 PM EST (03:00 UTC next day)
]