// https://catalog.yale.edu/ycps/building-abbreviations/
export const RESIDENTIAL_COLLEGES = [
	{
		name: "Benjamin Franklin",
		abbreviation: "BF",
	},
	{
		name: "Berkeley",
		abbreviation: "BK",
	},
	{
		name: "Branford",
		abbreviation: "BR",
	},
	{
		name: "Davenport",
		abbreviation: "DC",
	},
	{
		name: "Ezra Stiles",
		abbreviation: "ES",
	},
	{
		name: "Grace Hopper",
		abbreviation: "GH",
	},
	{
		name: "Jonathan Edwards",
		abbreviation: "JE",
	},
	{
		name: "Morse",
		abbreviation: "MC",
	},
	{
		name: "Pauli Murray",
		abbreviation: "MY",
	},
	{
		name: "Pierson",
		abbreviation: "PC",
	},
	{
		name: "Saybrook",
		abbreviation: "SY",
	},
	{
		name: "Silliman",
		abbreviation: "SM",
	},
	{
		name: "Timothy Dwight",
		abbreviation: "TD",
	},
	{
		name: "Trumbull",
		abbreviation: "TC",
	},
] as const;

export type ResidentialCollege = (typeof RESIDENTIAL_COLLEGES)[number];

export const RESIDENTIAL_COLLEGE_NAMES = [
	"Benjamin Franklin",
	"Berkeley",
	"Branford",
	"Davenport",
	"Ezra Stiles",
	"Grace Hopper",
	"Jonathan Edwards",
	"Morse",
	"Pauli Murray",
	"Pierson",
	"Saybrook",
	"Silliman",
	"Timothy Dwight",
	"Trumbull",
] as const satisfies readonly ResidentialCollege["name"][];

export const RESIDENTIAL_COLLEGE_ABBREVIATIONS = [
	"BF",
	"BK",
	"BR",
	"DC",
	"ES",
	"GH",
	"JE",
	"MC",
	"MY",
	"PC",
	"SY",
	"SM",
	"TD",
	"TC",
] as const satisfies readonly ResidentialCollege["abbreviation"][];

export const DINING_HALL_NAMES = [
	"Commons",
	...RESIDENTIAL_COLLEGE_NAMES,
] as const;

export const MAJORS = [
	"African American Studies",
	"African Studies",
	"American Studies",
	"Anthropology",
	"Applied Mathematics",
	"Applied Physics",
	"Archaeological Studies",
	"Architecture",
	"Art",
	"Astronomy",
	"Astrophysics",
	"Biomedical Engineering",
	"Chemical Engineering",
	"Chemistry",
	"Classical Civilization",
	"Classics",
	"Cognitive Science",
	"Comparative Literature",
	"Computer Science",
	"Computer Science and Economics",
	"Computer Science and Mathematics",
	"Computer Science and Psychology",
	"Computing and Linguistics",
	"Computing and the Arts",
	"Earth and Planetary Sciences",
	"East Asian Languages and Literatures",
	"East Asian Studies",
	"Ecology and Evolutionary Biology",
	"Economics",
	"Economics and Mathematics",
	"Electrical Engineering",
	"Electrical Engineering and Computer Science",
	"Engineering Sciences (Chemical)",
	"Engineering Sciences (Electrical)",
	"Engineering Sciences (Environmental)",
	"Engineering Sciences (Mechanical)",
	"English",
	"Environmental Engineering",
	"Environmental Studies",
	"Ethics, Politics, and Economics",
	"Ethnicity, Race, and Migration",
	"Film and Media Studies",
	"French",
	"German Studies",
	"Global Affairs",
	"Greek, Ancient and Modern",
	"History",
	"History of Art",
	"History of Science, Medicine, and Public Health",
	"Humanities",
	"Italian Studies",
	"Jewish Studies",
	"Latin American Studies",
	"Linguistics",
	"Mathematics",
	"Mathematics and Philosophy",
	"Mathematics and Physics",
	"Mechanical Engineering",
	"Modern Middle East Studies",
	"Molecular Biophysics and Biochemistry",
	"Molecular, Cellular, and Developmental Biology",
	"Music",
	"Near Eastern Languages and Civilizations",
	"Neuroscience",
	"Philosophy",
	"Physics",
	"Physics and Geosciences",
	"Physics and Philosophy ",
	"Political Science",
	"Portuguese",
	"Psychology",
	"Religious Studies",
	"Russian",
	"Russian, East European, and Eurasian Studies",
	"Sociology",
	"South Asian Studies (second major only)",
	"Spanish",
	"Special Divisional Major",
	"Statistics and Data Science",
	"Theater, Dance, and Performance Studies",
	"Urban Studies",
	"Women’s, Gender, and Sexuality Studies",
] as const;
